# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  CODECOV_TOKEN: "4defc5a1-d45b-4536-a6ba-426802fa181e"

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    pypy3:
       python.version: 'pypy3'
       tox.env: 'pypy3'
    Python35:
      python.version: '3.5'
      tox.env: 'py35'
    Python36:
      python.version: '3.6'
      tox.env: 'py36'
    Python37:
      python.version: '3.7'
      tox.env: 'py37'
    Python38:
      python.version: '3.8'
      tox.env: 'py38'
    Linting:
        python.version: '3.7'
        tox.env: 'flake8'
    mypy:
      python.version: '3.7'
      tox.env: 'mypy'
    check-stubs:
      python.version: '3.7'
      tox.env: 'retype'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip tox
    pip install .[dev]
  displayName: 'Install dependencies'

- script: |
    tox -e $(tox.env)
  displayName: 'tox -e $(tox.env)'
